spring:
  application:
    name: enrollment-service

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5432/enrollment-service
    username: zeph
    password: zeph

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/test_realm
          jwk-set-uri: http://localhost:8181/realms/test_realm/protocol/openid-connect/certs


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/