spring:
  application:
    name: config

  cloud:
    config:
      server:
        git:
          uri: file:./config/configurations
          default-label: main
          clone-on-start: true

  rabbitmq:
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: env

server:
  port: 8888