spring:
  application:
    name: config

  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/hilcoe/senior/ORCS/config/configurations
  rabbitmq:
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: env

server:
  port: 8888