spring:
  application:
    name: curriculum-service

  config:
    import: optional:configserver:http://localhost:8888

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
